name: dev
channels:
  - conda-forge
  - defaults
channel_priority: 'strict'
dependencies:
  - numpy=1.22.3
  - python-dateutil=2.8.1
  - pytz=2021.3
  - numexpr=2.7.2
  - bottleneck=1.3.4
  - pandas=1.4.1
