name: pandas
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g dockerlint
      - run: cd pandas && dockerlint

  publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Get changed files
        id: changed-pandas-files
        uses: tj-actions/changed-files@v17.3
        with:
          files: |
            ./pandas
      - name: Publish pandas image if changed
        if: steps.changed-pandas-files.outputs.only_changed == 'true'
        run: |
          cd pandas
          make dist
          make jupyter
          make publish
